package com.housedash.domain.money

enum class HoldFault {
    MALFORMED_ID,
    UNKNOWN_STATE,
    NEGATIVE_FIGURE,
    PAID_OUT_MORE_THAN_CAPTURED,
    FIGURE_PRESENT_BEFORE_CAPTURE,
    CAPTURED_BELOW_ACCEPTED_TOTAL,
    PAID_OUT_WHILE_STILL_HELD,
    RELEASED_SHORT_OF_CAPTURED,
    RELEASED_WITHOUT_COMPLETION,
    RELEASED_WITHOUT_CONFIRMATION,
    RELEASE_GROUNDS_ABSENT,
    RELEASE_GROUNDS_PRESENT_BEFORE_RELEASE,
    REFUNDED_SHORT_OF_CAPTURED,
    PART_REFUND_DOES_NOT_ADD_UP_TO_CAPTURED,
}

class CorruptHold internal constructor(
    val fault: HoldFault,
) : IllegalStateException(fault.name)
